#! /bin/bash

this_file=$(realpath "$0")
this_dir=$(dirname "$(realpath "$0")")
echo "$this_file"
echo "$this_dir"
docs_folder="/home/main/.steam/steam/steamapps/compatdata/1716740/pfx/drive_c/users/steamuser/Documents/My Games/Starfield"

bash "$this_dir"/enable-archive-invalidation.sh "$docs_folder"
